//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FryGuys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fry
    {
        public int FryID { get; set; }
        public string Potato { get; set; }
        public string Cut { get; set; }
        public string Cook { get; set; }
        public string Season { get; set; }
        public string Sauce { get; set; }
        public string Topping { get; set; }
    }
}
